#!/bin/sh

cat  << EOF
VUE_APP_API=$1
VUE_APP_API_LOGIN=$2
VUE_APP_API_CADASTRO=$3
VUE_APP_API_SENHA=$4
VUE_APP_API_AVISO=$5
VUE_APP_API_SISTEMA=$6
VUE_APP_API_UTILITARIO=$7
VUE_APP_API_BUSCAR_FUNCIONARIO=$8
VUE_APP_API_RESETAR_SENHA=${9}
EOF
